/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 redbull.gltf --transform 
Files: redbull.gltf [2.86MB] > C:\Users\lokes\Downloads\redbull-can\redbull-transformed.glb [115.19KB] (96%)
Author: moonlightwalker (https://sketchfab.com/moonlightwalker066)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/redbull-can-3000bdef310f45f5b56bbeb4ab19376d
Title: redbull can
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function RedbullModel(props) {
  const { nodes, materials } = useGLTF('/redbull-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh 
      geometry={nodes.pCylinder7_aiStandardSurface1_0.geometry} 
      material={materials.aiStandardSurface1} 
      scale={[4.766, 13.402, 4.766]}
      position={[0,0,0]} />
    </group>
  )
}

useGLTF.preload('/redbull-transformed.glb')
